
spring.jpa.defer-datasource-initialization: true

server:
  port: 8092
  error:
    include-message: always
    include-binding-errors: always

#spring:
  #h2:
  #  console:
  #    enabled: true
  #datasource:
  #  url: jdbc:h2:mem:customerDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  #  driverClassName: org.h2.Driver
  #  platform: h2
  #  username: sa
  #  password:

  #jpa:
  #  show-sql: true
  #  hibernate:
  #    ddl-auto: update
  #  database-platform: org.hibernate.dialect.H2Dialect
  #  properties:
  #    hibernate:
  #      show_sql: true
  #      use_sql_comments: false
  #      format_sql: false
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/userdb
    username: webavanzada
    password: webavanzada
    driverClassName: org.postgresql.Driver

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
eureka:
  client:
    serviceUrl:
      defaultZone: http://52.73.98.2:8099/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
